#ifndef _COMMAND_H_
#define _COMMAND_H_

//Communication commands
#define COMMAND_FOLLOW0 2
#define COMMAND_FOLLOW1 4
#define COMMAND_FOLLOW2 8
#define COMMAND_FOLLOW3 16
#define COMMAND_180CL 	32
#define COMMAND_180CC	64
#define COMMAND_PARK 	128
#define COMMAND_REVERSEPARK	240
#define COMMAND_STOP	255

#define COMMAND_MODE	196
#define COMMAND_FORWARD	224
#define COMMAND_BACKWARD	192
#define COMMAND_LEFT	226
#define COMMAND_RIGHT	136

#endif